### ISSUE TITLE
转移种子计划执行完报错

### ISSUE THREAD

**Issue by taowaaCool** [ledccn/IYUUPlus#155]
QNAP TS453Bmini
Docker iyuu
已经正常配置通知，类型 IYUU。
转移完种子报错，转移正常，没有通知。求助这个要怎么解决？

```
II::::::II       Y:::::Y        U:::::::UUU:::::::U  U:::::::UUU:::::::U
I::::::::I    YYYY:::::YYYY      UU:::::::::::::UU    UU:::::::::::::UU
I::::::::I    Y:::::::::::Y        UU:::::::::UU        UU:::::::::UU
IIIIIIIIII    YYYYYYYYYYYYY          UUUUUUUUU            UUUUUUUUU
1696940748.7365 当前时间：2023-10-10 20:25:48
1696940748.7365 当前操作系统：Linux
1696940748.7366 当前运行环境：Linux
1696940748.7366 当前接口类型：cli
1696940748.7366 PHP二进制文件：/usr/bin/php7
1696940748.7366 PHP版本号：7.4.23
1696940748.7366 环境变量初始化完成！
1696940748.7367  检查配置，是否同时监听IPv6...
1696940748.7368  未检测到常规配置JSON文件。
1696940748.7379 当前脚本路径：/IYUU/bin/move.php
PHP Notice:  Undefined index: 453B in /IYUU/src/Notify/NotifyFactory.php on line 30
Notice: Undefined index: 453B in /IYUU/src/Notify/NotifyFactory.php on line 30
1696940748.7481 命令行参数解析完成！
qBittorrent 客户端正在实例化！
qBittorrent：http://192.168.5.121:8080 Rpc连接 [v4.5.5]
transmission 客户端正在实例化！
transmission：http://192.168.5.121:9091 Rpc连接 [success]
正在从下载器 clients_pid61_6524243f8235c 获取种子哈希……
...
...
...
clients_pid59_65242470e34e8是目标转移客户端，避免冲突，已跳过！
PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /IYUU/src/Reseed/AutoReseed.php:1003
Stack trace:
#0 /IYUU/src/Reseed/MoveTorrent.php(411): IYUU\Reseed\AutoReseed::send_notify()
#1 /IYUU/src/Reseed/MoveTorrent.php(71): IYUU\Reseed\MoveTorrent::job_done_notify()
#2 /IYUU/bin/move.php(12): IYUU\Reseed\MoveTorrent::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 1003
Fatal error: Uncaught Error: Call to a member function send() on null in /IYUU/src/Reseed/AutoReseed.php:1003
Stack trace:
#0 /IYUU/src/Reseed/MoveTorrent.php(411): IYUU\Reseed\AutoReseed::send_notify()
#1 /IYUU/src/Reseed/MoveTorrent.php(71): IYUU\Reseed\MoveTorrent::job_done_notify()
#2 /IYUU/bin/move.php(12): IYUU\Reseed\MoveTorrent::call()
#3 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 1003
```

**Comment by taowaaCool** [comment]
> clients_pid59_65242470e34e8是目标转移客户端，避免冲突，已跳过！ 这个我也遇到了不知道怎么回事 还有3000个种子无法转移

这个是正常的，是跳检验的。我的用起来功能都是正常的。就是会报错。
可能是这里的问题（PHP Notice:  Undefined index: 453B in /IYUU/src/Notify/NotifyFactory.php on line 30
Notice: Undefined index: 453B in /IYUU/src/Notify/NotifyFactory.php on line 30）

**Comment by taowaaCool** [comment]
已解决，把配置删除全新安装正常就可以正常使用了
