### ISSUE TITLE
PHP Fatal error 错误

### ISSUE THREAD

**Issue by dfbb9216** [ledccn/IYUUPlus#169]
PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /IYUU/src/Reseed/AutoReseed.php:1003
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(988): IYUU\Reseed\AutoReseed::send_notify()
#1 /IYUU/src/Reseed/AutoReseed.php(709): IYUU\Reseed\AutoReseed::cookieExpired()
#2 /IYUU/src/Reseed/AutoReseed.php(558): IYUU\Reseed\AutoReseed::selfClientReseed()
#3 /IYUU/src/Reseed/AutoReseed.php(454): IYUU\Reseed\AutoReseed::requestApi()
#4 /IYUU/src/Reseed/AutoReseed.php(397): IYUU\Reseed\AutoReseed::reseed()
#5 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#6 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 1003
Fatal error: Uncaught Error: Call to a member function send() on null in /IYUU/src/Reseed/AutoReseed.php:1003
Stack trace:
#0 /IYUU/src/Reseed/AutoReseed.php(988): IYUU\Reseed\AutoReseed::send_notify()
#1 /IYUU/src/Reseed/AutoReseed.php(709): IYUU\Reseed\AutoReseed::cookieExpired()
#2 /IYUU/src/Reseed/AutoReseed.php(558): IYUU\Reseed\AutoReseed::selfClientReseed()
#3 /IYUU/src/Reseed/AutoReseed.php(454): IYUU\Reseed\AutoReseed::requestApi()
#4 /IYUU/src/Reseed/AutoReseed.php(397): IYUU\Reseed\AutoReseed::reseed()
#5 /IYUU/bin/iyuu.php(12): IYUU\Reseed\AutoReseed::call()
#6 {main}
  thrown in /IYUU/src/Reseed/AutoReseed.php on line 1003

OPENWRT DOCKER安装的IYUU，然后TR客户端在WIN NAS上，之前没有这种报错，IYUU恢复后出现的

**Comment by dfbb9216** [comment]
重新安装了，好像解决了
