### ISSUE TITLE
应用日志里提示Warning: usleep() 

### ISSUE THREAD

**Issue by ywycd** [ledccn/IYUUPlus#2]
用的Arm64v8的docker镜像。

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

```PHP Fatal error:  Uncaught InvalidArgumentException: Invalid cron string: 05 10 */0.5 * * in /IYUU/vendor/workerman/crontab/src/Parser.php:64
Stack trace:
#0 /IYUU/vendor/workerman/crontab/src/Crontab.php(155): Workerman\Crontab\Parser->parse('05 10 */0.5 * *')
#1 /IYUU/vendor/workerman/workerman/Events/Select.php(232): Workerman\Crontab\Crontab::Workerman\Crontab\{closure}()
#2 /IYUU/vendor/workerman/workerman/Events/Select.php(281): Workerman\Events\Select->tick()
#3 /IYUU/vendor/workerman/workerman/Worker.php(2430): Workerman\Events\Select->loop()
#4 /IYUU/vendor/workerman/workerman/Worker.php(1555): Workerman\Worker->run()
#5 /IYUU/vendor/workerman/workerman/Worker.php(1385): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#6 /IYUU/vendor/workerman/workerman/Worker.php(1359): Workerman\Worker::forkWorkersForLinux()
#7 /IYUU/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#8 /IYUU/start.php(167): Workerman\Worker::runAll()
#9 {main}
  thrown in /IYUU/vendor/workerman/crontab/src/Parser.php on line 64

Fatal error: Uncaught InvalidArgumentException: Invalid cron string: 05 10 */0.5 * * in /IYUU/vendor/workerman/crontab/src/Parser.php:64
Stack trace:
#0 /IYUU/vendor/workerman/crontab/src/Crontab.php(155): Workerman\Crontab\Parser->parse('05 10 */0.5 * *')
#1 /IYUU/vendor/workerman/workerman/Events/Select.php(232): Workerman\Crontab\Crontab::Workerman\Crontab\{closure}()
#2 /IYUU/vendor/workerman/workerman/Events/Select.php(281): Workerman\Events\Select->tick()
#3 /IYUU/vendor/workerman/workerman/Worker.php(2430): Workerman\Events\Select->loop()
#4 /IYUU/vendor/workerman/workerman/Worker.php(1555): Workerman\Worker->run()
#5 /IYUU/vendor/workerman/workerman/Worker.php(1385): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#6 /IYUU/vendor/workerman/workerman/Worker.php(1359): Workerman\Worker::forkWorkersForLinux()
#7 /IYUU/vendor/workerman/workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#8 /IYUU/start.php(167): Workerman\Worker::runAll()
#9 {main}
  thrown in /IYUU/vendor/workerman/crontab/src/Parser.php on line 64
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/runtime/crontab/cron_dir/pid19_2250_6019fcab66d0a.crontab修改时间:2021-02-03 09:31:53
/IYUU/runtime/crontab/cron_dir/pid19_2250_6019fcab66d0a.crontab修改时间:2021-02-03 16:11:02
/IYUU/app/controller/Api.php update and reload
/IYUU/app/domain/Crontab.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/runtime/crontab/cron_dir/pid19_2250_6019fcab66d0a.crontab修改时间:2021-02-04 17:59:27
/IYUU/app/domain/Crontab.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/app/middleware/AuthCheck.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/app/controller/Task.php update and reload
/IYUU/app/controller/Task.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/app/domain/Reseed.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
/IYUU/runtime/crontab/cron_dir/pid19_2250_6019fcab66d0a.crontab修改时间:2021-02-07 10:27:01
/IYUU/app/controller/Api.php update and reload
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275
PHP Warning:  usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275

Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /IYUU/vendor/workerman/workerman/Events/Select.php on line 275```

**Comment by ledccn** [comment]
什么设备

**Comment by ywycd** [comment]
斐讯N1刷小钢炮，portainer网页端升到2.1.1
